### ISSUE TITLE
As an unregistered user I want to read the rules in order to understand how the game works. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#1]
## Acceptance Criteria
- [ ] The homepage displays the rules button. 
- [ ] By clicking on the rules button, you are redirected to the rules page. 
- [ ] The rules are displayed on the rules page. 

## Development Tasks
- [ ] sopra-fs23-group-05/Client#34
- [ ] sopra-fs23-group-05/Client#35
- [ ] sopra-fs23-group-05/Client#36
