### ISSUE TITLE
As a lobby leader I want to start the game in order to play the game. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#10]
- [x] The teams are stored in the database record, with an individual team id and a list of all its users. 
- [x] For every team, the users which have chosen the team are stored in the database record.
- [x] Game is stored in the database record. 

## Development Tasks
- [x] sopra-fs23-group-05/Server#51
- [x] sopra-fs23-group-05/Client#22
- [x] sopra-fs23-group-05/Client#23
- [x] sopra-fs23-group-05/Server#54
- [x] sopra-fs23-group-05/Client#24
