### ISSUE TITLE
As a player I want to see the correct content in order to fulfill my role in the current turn. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#11]
- [x] One card, chat box, timer, score of the active turn and a skip button are displayed to one team member (clue-giver) of team one (guesser team). 
- [x] The chat box, the timer and the score of the active turn are displayed to all other members of the guesser team. 
- [x] The card, a chat box, the timer, the score of the active turn and a buzzer are displayed to the members of team two (buzzer team). 

## Development Tasks
- [x] https://github.com/sopra-fs23-group-05/Client/issues/56
- [x] https://github.com/sopra-fs23-group-05/Client/issues/57
- [x] https://github.com/sopra-fs23-group-05/Client/issues/58
- [x] https://github.com/sopra-fs23-group-05/Client/issues/59
- [x] https://github.com/sopra-fs23-group-05/Client/issues/60
- [x] https://github.com/sopra-fs23-group-05/Client/issues/61
- [x] https://github.com/sopra-fs23-group-05/Client/issues/62
- [x] sopra-fs23-group-05/Server#66
- [x] sopra-fs23-group-05/Server#67
- [x] sopra-fs23-group-05/Server#68
- [x] sopra-fs23-group-05/Server#70
- [x] sopra-fs23-group-05/Client#29
- [x] sopra-fs23-group-05/Server#73
- [x] sopra-fs23-group-05/Client#31

**Comment by felixmerz00** [comment]
## Development Tasks
- [ ] A new task
