### ISSUE TITLE
As a clue-giver I want to be able to click on the word I must describe, to see its definition.

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#14]
## Acceptence Criteria
- [x]  A small information field with a short definition is displayed if the user touches the taboo word button. 

## Development Tasks
- [x] sopra-fs23-group-05/Client#110

- [x] sopra-fs23-group-05/Client#1

- [x] sopra-fs23-group-05/Client#2
