### ISSUE TITLE
As the clue-giver, I want to be able to skip a card, to not waste time on a word I do not understand. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#15]
## Acceptance Criteria
- [x] The current card is discarded, and a new card is shown to all players. 
- [x] A malus of 1 is added to the turn score of the team. 

## Development Tasks

- [x] sopra-fs23-group-05/Client#3

- [x] sopra-fs23-group-05/Server#28

- [x] sopra-fs23-group-05/Server#29
