### ISSUE TITLE
As the opposing team I want to use the buzzer if a forbidden word is used, and the other team gets a minus point.  

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#16]
## Acceptance Criteria
- [x] If two or more people click the buzzer, a new card is shown to the clue-giver. 
- [x] The team score of the guessing team is decreased by one. 

## Development Tasks
- [x] sopra-fs23-group-05/Client#4
- [x] sopra-fs23-group-05/Server#31
- [x] sopra-fs23-group-05/Server#32
