### ISSUE TITLE
As a guessing player I want to enter a guess into the chat box to receive points. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#18]
## Acceptance Criteria
- [x] The text entered by the guessing player is sent to the backend to check if the guess is correct. 
- [x] The guess is displayed to all users in the chat box. 
- [x] If the text matches the solution the guessing team receives a point. 
- [x] If one player guessed the correct word, a new card is displayed automatically and the round continues, until the timer runs out 
- [x] If the text does not match the solution, the user can continue writing guesses in the chat box. 

## Development Tasks
- [x] sopra-fs23-group-05/Client#7
- [x] https://github.com/sopra-fs23-group-05/Client/issues/65
- [x] https://github.com/sopra-fs23-group-05/Server/issues/118
- [x] https://github.com/sopra-fs23-group-05/Client/issues/66
- [x] sopra-fs23-group-05/Server#45
- [x] sopra-fs23-group-05/Server#46
- [x] https://github.com/sopra-fs23-group-05/Server/issues/120
