### ISSUE TITLE
As a player, I want to know the total score of the teams at the end of the game, so I know which team won the game. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#22]
## Acceptance Criteria
- [x] After n number of rounds the game finishes automatically. 
- [x] On the final page the results of the two teams are displayed and it is indicated which team won the match. 
- [x] The final page contains a button to go back to the home page. 
- [x] The final page contains a share button to share a player's score on Twitter. 

## Development Tasks
- [x] sopra-fs23-group-05/Client#106
- [x] sopra-fs23-group-05/Client#10
- [x] sopra-fs23-group-05/Client#11
- [x] sopra-fs23-group-05/Client#12
