### ISSUE TITLE
As an unregistered lobby leader, I want to type in my username in the corresponding field on the login page in order to create a lobby. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#3]
## Acceptance Criteria
- [x] By clicking on enter, you are redirected to the lobby page. 
- [x] The lobby page contains a start game button, a settings button, invite button and a list of joined players. 
- [x] You can only access the lobby page if you give yourself a username. 
- [x] The lobby leader’s username, his individual user id and a lobby leader identifier are stored in the database record. 
- [x] A lobby object is stored in the database record. 

## Development Tasks
- [x] #97
- [x] sopra-fs23-group-05/Server#86
- [x] sopra-fs23-group-05/Server#87
- [ ] sopra-fs23-group-05/Server#88
- [ ] sopra-fs23-group-05/Client#39
- [ ] sopra-fs23-group-05/Client#42
- [x] sopra-fs23-group-05/Client#40
- [x] sopra-fs23-group-05/Server#91
- [x] sopra-fs23-group-05/Client#41
