### ISSUE TITLE
As an unregistered user who is not a lobby leader, I want to login with either an access code, an invite link or a QR code. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#4]
## Acceptance Criteria
- [x] A login page with one field for the username and one field for the access code is displayed. Also, a join button is displayed. 
- [x] After scanning a QR-Code or clicking on an invite link, the access code will automatically be entered into the corresponding field. 

## Development Tasks
- [x] sopra-fs23-group-05/Client#43
- [x] sopra-fs23-group-05/Client#44
- [x] sopra-fs23-group-05/Server#96
