### ISSUE TITLE
As an unregistered user, I want to log into the shared game lobby in order to play with other users. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#5]
## Acceptance Criteria
- [x] The user’s username and an individual user id are stored in the database record. 
- [x] Logged-in users can see the names of all other players as soon as they select a team. 
- [x] Upon failure, an error is displayed, and user is redirected to login screen (login error can be, that the lobby is closed, or username is already taken). 

## Development Tasks
- [x] sopra-fs23-group-05/Server#99
- [x] sopra-fs23-group-05/Server#100
- [x] sopra-fs23-group-05/Client#45
