### ISSUE TITLE
As a registered user, I want to choose between two groups to play in this team. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#8]
- [x] When clicking on the join button, my name is displayed in the section dedicated to the team I have chosen. 

## Development Tasks

- [x] sopra-fs23-group-05/Client#13
- [x] sopra-fs23-group-05/Client#14
- [x] sopra-fs23-group-05/Client#15
- [x] sopra-fs23-group-05/Server#75
- [x] sopra-fs23-group-05/Server#76
- [x] sopra-fs23-group-05/Server#78
- [x] sopra-fs23-group-05/Server#79
- [x] sopra-fs23-group-05/Client#21
- [x] https://github.com/sopra-fs23-group-05/Server/issues/150
